### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by resoli** [nowina-solutions/nexu#1]
Hello,
I tried to build with

mvn clean install

as of README, but  I get an "Unable to resolve artifact", caused by missing:

https://joinup.ec.europa.eu/nexus/content/groups/public//eu/europa/ec/joinup/sd-dss/dss-spi/4.6-SNAPSHOT/dss-spi-4.6-20150909.155355-4.jar

bye,
rob

PS: Great project, close following it.

**Comment by naramski** [comment]
I tried several times to build with success. The only difference I notice is that my build fetch : 

https://joinup.ec.europa.eu/nexus/content/groups/public/eu/europa/ec/joinup/sd-dss/dss-spi/4.6-SNAPSHOT/dss-spi-4.6-20150909.155353-3.jar

Instead of 

https://joinup.ec.europa.eu/nexus/content/groups/public//eu/europa/ec/joinup/sd-dss/dss-spi/4.6-SNAPSHOT/dss-spi-4.6-20150909.155355-4.jar

Can you try again with a clean maven repository ?

**Comment by resoli** [comment]
I completely reset my maven installation. Works now :-) 
Thanks,
rob

**Comment by resoli** [comment]
I tried to show certificates on my Italian PKCS11 smartcard ( http://localhost:9876/rest/certificates ) .
No success, server reports: 
> ott 21, 2015 12:25:25 PM lu.nowina.nexu.flow.TokenFlow createToken
INFORMAZIONI: 0 card detected

I reported ATR (3b:ff:18:00:ff:81:31:fe:55:00:6b:02:09:03:03:01:11:01:43:4e:53:11:31:80:8c) in the subsequent dialog asking for info. It's an italian card issued by Infocert CA. Chip is Incard if I remember correctly.

**Comment by resoli** [comment]
PS: If you want I can open a separate Issue.

**Comment by naramski** [comment]
It is better to create a separate issue, indeed. I can do it, but you wont be notofied on reply. 
It's strange that the software detect no smartcard, as it only list what is available through smartcard.io.
You may look to the class CardDetector in package "lu.nowina.nexu.smartcard.dector" of nexu-core. 
Can you try again and start NexU only when your smartcard and smartcard reader are pluged in ?

**Comment by resoli** [comment]
Sorry, I have some doubts about the correct steps to start the app. After building, I have:

> 1) cd nexu-app/target/
> 2) java -cp nexu-app-1.0.RC1.jar lu.nowina.nexu.NexUApp

Is it correct?

**Comment by resoli** [comment]
Il 21/10/2015 16:00, David Naramski ha scritto:
> It is better to create a separate issue, indeed. I can do it, but you
> wont be notofied on reply.
> It's strange that the software detect no smartcard, as it only list what
> is available through smartcard.io.
> You may look to the class CardDetector in package
> "lu.nowina.nexu.smartcard.dector" of nexu-core.
> Can you try again and start NexU only when your smartcard and smartcard
> reader are pluged in ?


Sorry, I have some doubts about the correct steps to start the app.
After building, I have:

    1) cd nexu-app/target/bundles
    2) java -cp nexu-app-1.0.RC1.jar lu.nowina.nexu.NexUApp

Is it correct?

rob

**Comment by naramski** [comment]
Yes it is correct. You should also have a MSI in the "target/bundle"

**Comment by resoli** [comment]
Il 22/10/2015 08:57, David Naramski ha scritto:
> Yes it is correct. You should also have a MSI in the "target/bundle"

nexu-1.0-1.x86_64.rpm  nexu-1.0.deb (I'm on Ubuntu wily) not tried to 
install the deb

rob

**Comment by georgiev-georgi** [comment]
Hello, 
I've tried to build the project, but the following error appears:

[ERROR] Failed to execute goal on project nexu-api: Could not resolve dependencies for project lu.nowina.apps:nexu-api:jar:1.10.2: Could not find artifact eu.europa.ec.joinup.sd-dss:dss-spi:jar:4.6.0 in joinup-dss-thirdparty (http://joinup.ec.europa.eu/site/sd-dss/maven2) -> [Help 1]

My local maven directory is empty when I try to execute mvn clean install for the first time. I've tried to build the following branches: master/nexu-1.10.2/nexu-1.10-hotfixes, but the error is the same.
I saw this post https://joinup.ec.europa.eu/news/sd-dss-project-nexus-repos and changed the 
url http://joinup.ec.europa.eu/site/sd-dss/maven2 inside the pom.xml to 
https://joinup.ec.europa.eu/nexus/content/repositories/releases/eu/europa/ec/joinup/sd-dss/ but it didn't help. 

Do you have any ideas?

**Comment by georgiev-georgi** [comment]
Finally I've built the code, but  I had to download the sd-dss project from https://github.com/esig/dss and to build the 4.6.0 version before building the nexu.
