### ISSUE TITLE
NexU as Chrome and Firefox extension

### ISSUE THREAD

**Issue by vakho10** [nowina-solutions/nexu#17]
Hi guys, I've thought about the idea of making NexU extension for Chrome and Firefox browsers. They have the same interface and support native messaging (which means calling native application from browser's extension). Wouldn't it be a good edition for NexU?

**Comment by naramski** [comment]
Hi ! 

Many thanks for your suggestion. We are aware of other projects that have followed this idea (like https://www.id.ee/?id=36798). I don't have a lot of feedback about those. 

But currently, NexU aims to be a Software Agent deployed on the computer. We have the feeling that maintaining plusieurs plugins in a environment like the browser will be a big effort. Maybe if we see that all the browsers are going to use the same API, like for Edge and Chrome.... 

Kind regards,
