### ISSUE TITLE
Integration documentation and linux builds

### ISSUE THREAD

**Issue by igorbga** [nowina-solutions/nexu#21]
Hi:
This is just a questin not a bug but didn't find a better place to ask.
Is there any kind of integration documentation that helps developing the interaction between Javascript and Nexu?

In the web I read that there are also Linux packages available but couldn't find them. Are they publically release or are they just for nowina's customers?

Thanks

**Comment by naramski** [comment]
Hi ! For the open-source core of NexU, the source code is currently the best documentation. We may add documentation in the source code, but it is not on the roadmap so far. 

for the Linux package, you can of course create your own based on the source code, but currently we maintain them only for the NexU Pro release. 

Kind regards
