### ISSUE TITLE
NexU not detected error

### ISSUE THREAD

**Issue by urvishmparikh** [nowina-solutions/nexu#3]
Hi,

We are interested in this solution. We build complete project and launch nexu -startup.bat.
It launch application but when we tried to see demo it always says nexu not detected.

It looks several issues from nexu log file.
By default binding port is binding_ports=9776 but try to connect 9876.
2016-03-07 15:00:35,721 INFO  [NexuLauncher] no http://127.0.0.1:9876/info detected, Connection refused: connect

Is there any documentation for this? How is it work and flow information?

Kr,
Urvish

**Comment by urvishmparikh** [comment]
It seems ok as app is running on 9876 while demo on browser pointing to 9876 due to that nexu not detected..

**Comment by jlepropre** [comment]
Hi,

Demo available at http://lab.nowina.solutions/nexu-demo/ is intended to work only with commercial demo version available at http://nowina.lu/nexu/register-to-download-nexu/ and not with the community version.

For information, the version 1.4 of commercial demo version has just been released yesterday.

Best regards,
Jean.
