### ISSUE TITLE
Https

### ISSUE THREAD

**Issue by coupej** [nowina-solutions/nexu#4]
I could get the project to work, but I can't seem to get it to work with https. 

I get a net::ERR_SSL_PROTOCOL_ERROR error.

![schermafbeelding 2016-08-23 om 16 22 54](https://cloud.githubusercontent.com/assets/912039/17895597/e64f391a-694d-11e6-8ac4-355f28dd5c05.png)

I allready tried some options like  compiling with the "lu.nowina.nexu.https.HttpsPlugin" plugin, but I can't seem to make it work. 

Is there support for https? What steps should one take to get it to work? 

thanks in advance.

**Comment by jlepropre** [comment]
Hello,

Target ports for the community version are:
- 9795 for HTTP
- 9895 for HTTPS

Best regards,
Jean.

**Comment by coupej** [comment]
Dear Jean, 

Thx for the response. Using version 1.6 it seems to work for me on port 9896. However due to the certificate being self-signed i needed to add an exception to the browser (both FF en Chrome) to allow a self-signed certificate for localhost. 

What is the recommended way of dealing with this so end-user wouldn't need to do this? 

Best regards 
Jeroen

**Comment by jlepropre** [comment]
Dear Jeroen,

At **NexU startup**, the HttpsPlugin will normally install the self signed certificate in Windows and Firefox stores (Chrome and IE use the Windows store, only Firefox has its own store).

If you had to add an exception, it means that:
- You did not restart your Firefox/Chrome after certificate installation.
- For Chrome, installation in Windows store failed (but a pop-up is shown in this last case).
- You use Linux/Mac OS X in which case the code to install certificates is not yet available.

Hope it helps.

Best regards,
Jean.

**Comment by coupej** [comment]
That explains it, I was testing on max OS X.

Thanks for your swift feedback and for creating the solution.

**Comment by jlepropre** [comment]
You are welcome!

**Comment by vividuranv** [comment]
Hi everyone! How did you make https work? In my machine only starts the http server in port 9886, the https port doesn't start. I have spend many hours trying and investigating but I can't make it work. I have windows 10 and I'm using Chrome and Firefox and this program NexU-1.6-per-user-x64-en.msi

Thanks in advance!

**Comment by louki99** [comment]
what is mean this error "an error has occurred when nexu tried to install certificate in Linux Firefox stores" whine try to run nexu.jar in linux (ubuntu) any hep ?
