### ISSUE TITLE
msi not build

### ISSUE THREAD

**Issue by trigouts** [nowina-solutions/nexu#5]
Hello,

I have just downloaded and built v 1.6 using mvn clean install.

After build there is no msi file generated however, which we need in order to have the keystore installed for https connection.

PFA a screenshot of the content of the bundle.zip

bye,
![nexu-bundle](https://cloud.githubusercontent.com/assets/6457504/17964411/56a3e780-6ab9-11e6-81ae-ab63eb023966.PNG)

tom

**Comment by jlepropre** [comment]
Hello Tom,

There is no MSI in the community version.

However it is not required to install the keystore. At NexU startup, the HttpsPlugin will normally install the self signed certificate in Windows and Firefox stores (Chrome and IE use the Windows store, only Firefox has its own store).

If no certificate was installed, it means that:
- You did not restart your Firefox/Chrome after certificate installation.
- For Chrome, installation in Windows store failed (but a pop-up is shown in this last case).
- You use Linux/Mac OS X in which case the code to install certificates is not yet available.

Hope it helps.

Best regards,
Jean.

**Comment by trigouts** [comment]
Jean,

Thanks for your reply.

I have another question : is getIdentityInfo supported in the community flow since I am getting a "Flow not recognized/not implemented in this version." nullpointer exception.

regards,

Tom

**Comment by jlepropre** [comment]
Dear Tom,

No, the get identity information feature is not available in the community version, as it requires a plugin specific to the card(s) from which you wish to get the information.

Best regards,
Jean.

**Comment by jlepropre** [comment]
Dear Tom,

I will close this issue, as I think that it is now solved.

If it is not the case, do not hesitate to reopen it, or open a new one.

Best regards,
Jean.
