### ISSUE TITLE
Signature field.

### ISSUE THREAD

**Issue by birosat** [nowina-solutions/nexu#8]
How to make signature field visible?

**Comment by jlepropre** [comment]
Hello,

Thank you very much for your message and interest for NexU.

The requested feature (make signature field visible) is not part of NexU. Indeed, NexU allows (web) applications to communicate with signature means (smartcards, keystores, etc.) using modern protocols and mechanisms (without Java applets). So NexU allows you to retrieve certificates, **compute** signature, authenticate or get identity information, but not to sign a document.

To sign documents and so make signature field visible, I suggest you to use SD-DSS (https://github.com/esig/dss) or EVA Platform (http://nowina.lu/solutions/#EVA).

Best regards,
Jean Lepropre.

**Comment by birosat** [comment]
Thanks for reply :-).
