### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jose-carvalho** [nowina-solutions/nexu#9]
the project hasnt been updated in a very long time, is it dead? 
I know that this is not a real issue, but dont know where to put the question.. Thanks

**Comment by naramski** [comment]
Hello. Thanks for your interest in NexU. The project is alive and well, thanks.

**Comment by jose-carvalho** [comment]
thanks for the answer. :) closing the issue. ;)

**Comment by unguul** [comment]
![image](https://github.com/nowina-solutions/nexu/assets/7005614/01274dc8-0089-4d75-a577-55bf41c893c0)

**Comment by hello-earth-gh** [comment]
Apparently, it seems that there is no more active development by Nowina that originally created this project. There are some more recent forks around (I created one, and it is still actively used by a number of users as part of digital signing procedures involved with DSS), but they are not maintained by the community, i.e. there is no community-approved maintenance process that would give this project more credibility than it already has. i actually don't even know about the alternatives. i wish we had a clearer picture.

**Comment by unguul** [comment]
@hello-earth-gh Same here! I actually noticed your fork of this too so good job!
